/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.my.rdd;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class WeatherData extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"WeatherData\",\"namespace\":\"com.my.rdd\",\"fields\":[{\"name\":\"stationId\",\"type\":\"string\"},{\"name\":\"year\",\"type\":\"string\"},{\"name\":\"month\",\"type\":\"string\"},{\"name\":\"day\",\"type\":\"string\"},{\"name\":\"meanTemp\",\"type\":\"double\"},{\"name\":\"meanTempCount\",\"type\":\"int\"},{\"name\":\"meanDewPointTemp\",\"type\":\"double\"},{\"name\":\"meanDewPointTempCount\",\"type\":\"int\"},{\"name\":\"meanSeaLevelPressure\",\"type\":\"double\"},{\"name\":\"meanSeaLevelPressureCount\",\"type\":\"int\"},{\"name\":\"meanStationPressure\",\"type\":\"double\"},{\"name\":\"meanStationPressureCount\",\"type\":\"int\"},{\"name\":\"meanVisibility\",\"type\":\"double\"},{\"name\":\"meanVisibilityCount\",\"type\":\"int\"},{\"name\":\"meanWindSpeed\",\"type\":\"double\"},{\"name\":\"meanWindSpeedCount\",\"type\":\"int\"},{\"name\":\"maxSustainedWindSpeed\",\"type\":\"double\"},{\"name\":\"maxGustWindSpeed\",\"type\":\"double\"},{\"name\":\"maxTemp\",\"type\":\"double\"},{\"name\":\"maxTempFlag\",\"type\":\"string\"},{\"name\":\"minTemp\",\"type\":\"double\"},{\"name\":\"minTempFlag\",\"type\":\"string\"},{\"name\":\"totalPrecipitation\",\"type\":\"double\"},{\"name\":\"totalPrecipitationFlag\",\"type\":\"string\"},{\"name\":\"snowDepth\",\"type\":\"double\"},{\"name\":\"hasFog\",\"type\":\"boolean\"},{\"name\":\"hasRain\",\"type\":\"boolean\"},{\"name\":\"hasSnow\",\"type\":\"boolean\"},{\"name\":\"hasHail\",\"type\":\"boolean\"},{\"name\":\"hasThunder\",\"type\":\"boolean\"},{\"name\":\"hasTornado\",\"type\":\"boolean\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence stationId;
  @Deprecated public java.lang.CharSequence year;
  @Deprecated public java.lang.CharSequence month;
  @Deprecated public java.lang.CharSequence day;
  @Deprecated public double meanTemp;
  @Deprecated public int meanTempCount;
  @Deprecated public double meanDewPointTemp;
  @Deprecated public int meanDewPointTempCount;
  @Deprecated public double meanSeaLevelPressure;
  @Deprecated public int meanSeaLevelPressureCount;
  @Deprecated public double meanStationPressure;
  @Deprecated public int meanStationPressureCount;
  @Deprecated public double meanVisibility;
  @Deprecated public int meanVisibilityCount;
  @Deprecated public double meanWindSpeed;
  @Deprecated public int meanWindSpeedCount;
  @Deprecated public double maxSustainedWindSpeed;
  @Deprecated public double maxGustWindSpeed;
  @Deprecated public double maxTemp;
  @Deprecated public java.lang.CharSequence maxTempFlag;
  @Deprecated public double minTemp;
  @Deprecated public java.lang.CharSequence minTempFlag;
  @Deprecated public double totalPrecipitation;
  @Deprecated public java.lang.CharSequence totalPrecipitationFlag;
  @Deprecated public double snowDepth;
  @Deprecated public boolean hasFog;
  @Deprecated public boolean hasRain;
  @Deprecated public boolean hasSnow;
  @Deprecated public boolean hasHail;
  @Deprecated public boolean hasThunder;
  @Deprecated public boolean hasTornado;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public WeatherData() {}

  /**
   * All-args constructor.
   */
  public WeatherData(java.lang.CharSequence stationId, java.lang.CharSequence year, java.lang.CharSequence month, java.lang.CharSequence day, java.lang.Double meanTemp, java.lang.Integer meanTempCount, java.lang.Double meanDewPointTemp, java.lang.Integer meanDewPointTempCount, java.lang.Double meanSeaLevelPressure, java.lang.Integer meanSeaLevelPressureCount, java.lang.Double meanStationPressure, java.lang.Integer meanStationPressureCount, java.lang.Double meanVisibility, java.lang.Integer meanVisibilityCount, java.lang.Double meanWindSpeed, java.lang.Integer meanWindSpeedCount, java.lang.Double maxSustainedWindSpeed, java.lang.Double maxGustWindSpeed, java.lang.Double maxTemp, java.lang.CharSequence maxTempFlag, java.lang.Double minTemp, java.lang.CharSequence minTempFlag, java.lang.Double totalPrecipitation, java.lang.CharSequence totalPrecipitationFlag, java.lang.Double snowDepth, java.lang.Boolean hasFog, java.lang.Boolean hasRain, java.lang.Boolean hasSnow, java.lang.Boolean hasHail, java.lang.Boolean hasThunder, java.lang.Boolean hasTornado) {
    this.stationId = stationId;
    this.year = year;
    this.month = month;
    this.day = day;
    this.meanTemp = meanTemp;
    this.meanTempCount = meanTempCount;
    this.meanDewPointTemp = meanDewPointTemp;
    this.meanDewPointTempCount = meanDewPointTempCount;
    this.meanSeaLevelPressure = meanSeaLevelPressure;
    this.meanSeaLevelPressureCount = meanSeaLevelPressureCount;
    this.meanStationPressure = meanStationPressure;
    this.meanStationPressureCount = meanStationPressureCount;
    this.meanVisibility = meanVisibility;
    this.meanVisibilityCount = meanVisibilityCount;
    this.meanWindSpeed = meanWindSpeed;
    this.meanWindSpeedCount = meanWindSpeedCount;
    this.maxSustainedWindSpeed = maxSustainedWindSpeed;
    this.maxGustWindSpeed = maxGustWindSpeed;
    this.maxTemp = maxTemp;
    this.maxTempFlag = maxTempFlag;
    this.minTemp = minTemp;
    this.minTempFlag = minTempFlag;
    this.totalPrecipitation = totalPrecipitation;
    this.totalPrecipitationFlag = totalPrecipitationFlag;
    this.snowDepth = snowDepth;
    this.hasFog = hasFog;
    this.hasRain = hasRain;
    this.hasSnow = hasSnow;
    this.hasHail = hasHail;
    this.hasThunder = hasThunder;
    this.hasTornado = hasTornado;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return stationId;
    case 1: return year;
    case 2: return month;
    case 3: return day;
    case 4: return meanTemp;
    case 5: return meanTempCount;
    case 6: return meanDewPointTemp;
    case 7: return meanDewPointTempCount;
    case 8: return meanSeaLevelPressure;
    case 9: return meanSeaLevelPressureCount;
    case 10: return meanStationPressure;
    case 11: return meanStationPressureCount;
    case 12: return meanVisibility;
    case 13: return meanVisibilityCount;
    case 14: return meanWindSpeed;
    case 15: return meanWindSpeedCount;
    case 16: return maxSustainedWindSpeed;
    case 17: return maxGustWindSpeed;
    case 18: return maxTemp;
    case 19: return maxTempFlag;
    case 20: return minTemp;
    case 21: return minTempFlag;
    case 22: return totalPrecipitation;
    case 23: return totalPrecipitationFlag;
    case 24: return snowDepth;
    case 25: return hasFog;
    case 26: return hasRain;
    case 27: return hasSnow;
    case 28: return hasHail;
    case 29: return hasThunder;
    case 30: return hasTornado;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: stationId = (java.lang.CharSequence)value$; break;
    case 1: year = (java.lang.CharSequence)value$; break;
    case 2: month = (java.lang.CharSequence)value$; break;
    case 3: day = (java.lang.CharSequence)value$; break;
    case 4: meanTemp = (java.lang.Double)value$; break;
    case 5: meanTempCount = (java.lang.Integer)value$; break;
    case 6: meanDewPointTemp = (java.lang.Double)value$; break;
    case 7: meanDewPointTempCount = (java.lang.Integer)value$; break;
    case 8: meanSeaLevelPressure = (java.lang.Double)value$; break;
    case 9: meanSeaLevelPressureCount = (java.lang.Integer)value$; break;
    case 10: meanStationPressure = (java.lang.Double)value$; break;
    case 11: meanStationPressureCount = (java.lang.Integer)value$; break;
    case 12: meanVisibility = (java.lang.Double)value$; break;
    case 13: meanVisibilityCount = (java.lang.Integer)value$; break;
    case 14: meanWindSpeed = (java.lang.Double)value$; break;
    case 15: meanWindSpeedCount = (java.lang.Integer)value$; break;
    case 16: maxSustainedWindSpeed = (java.lang.Double)value$; break;
    case 17: maxGustWindSpeed = (java.lang.Double)value$; break;
    case 18: maxTemp = (java.lang.Double)value$; break;
    case 19: maxTempFlag = (java.lang.CharSequence)value$; break;
    case 20: minTemp = (java.lang.Double)value$; break;
    case 21: minTempFlag = (java.lang.CharSequence)value$; break;
    case 22: totalPrecipitation = (java.lang.Double)value$; break;
    case 23: totalPrecipitationFlag = (java.lang.CharSequence)value$; break;
    case 24: snowDepth = (java.lang.Double)value$; break;
    case 25: hasFog = (java.lang.Boolean)value$; break;
    case 26: hasRain = (java.lang.Boolean)value$; break;
    case 27: hasSnow = (java.lang.Boolean)value$; break;
    case 28: hasHail = (java.lang.Boolean)value$; break;
    case 29: hasThunder = (java.lang.Boolean)value$; break;
    case 30: hasTornado = (java.lang.Boolean)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'stationId' field.
   */
  public java.lang.CharSequence getStationId() {
    return stationId;
  }

  /**
   * Sets the value of the 'stationId' field.
   * @param value the value to set.
   */
  public void setStationId(java.lang.CharSequence value) {
    this.stationId = value;
  }

  /**
   * Gets the value of the 'year' field.
   */
  public java.lang.CharSequence getYear() {
    return year;
  }

  /**
   * Sets the value of the 'year' field.
   * @param value the value to set.
   */
  public void setYear(java.lang.CharSequence value) {
    this.year = value;
  }

  /**
   * Gets the value of the 'month' field.
   */
  public java.lang.CharSequence getMonth() {
    return month;
  }

  /**
   * Sets the value of the 'month' field.
   * @param value the value to set.
   */
  public void setMonth(java.lang.CharSequence value) {
    this.month = value;
  }

  /**
   * Gets the value of the 'day' field.
   */
  public java.lang.CharSequence getDay() {
    return day;
  }

  /**
   * Sets the value of the 'day' field.
   * @param value the value to set.
   */
  public void setDay(java.lang.CharSequence value) {
    this.day = value;
  }

  /**
   * Gets the value of the 'meanTemp' field.
   */
  public java.lang.Double getMeanTemp() {
    return meanTemp;
  }

  /**
   * Sets the value of the 'meanTemp' field.
   * @param value the value to set.
   */
  public void setMeanTemp(java.lang.Double value) {
    this.meanTemp = value;
  }

  /**
   * Gets the value of the 'meanTempCount' field.
   */
  public java.lang.Integer getMeanTempCount() {
    return meanTempCount;
  }

  /**
   * Sets the value of the 'meanTempCount' field.
   * @param value the value to set.
   */
  public void setMeanTempCount(java.lang.Integer value) {
    this.meanTempCount = value;
  }

  /**
   * Gets the value of the 'meanDewPointTemp' field.
   */
  public java.lang.Double getMeanDewPointTemp() {
    return meanDewPointTemp;
  }

  /**
   * Sets the value of the 'meanDewPointTemp' field.
   * @param value the value to set.
   */
  public void setMeanDewPointTemp(java.lang.Double value) {
    this.meanDewPointTemp = value;
  }

  /**
   * Gets the value of the 'meanDewPointTempCount' field.
   */
  public java.lang.Integer getMeanDewPointTempCount() {
    return meanDewPointTempCount;
  }

  /**
   * Sets the value of the 'meanDewPointTempCount' field.
   * @param value the value to set.
   */
  public void setMeanDewPointTempCount(java.lang.Integer value) {
    this.meanDewPointTempCount = value;
  }

  /**
   * Gets the value of the 'meanSeaLevelPressure' field.
   */
  public java.lang.Double getMeanSeaLevelPressure() {
    return meanSeaLevelPressure;
  }

  /**
   * Sets the value of the 'meanSeaLevelPressure' field.
   * @param value the value to set.
   */
  public void setMeanSeaLevelPressure(java.lang.Double value) {
    this.meanSeaLevelPressure = value;
  }

  /**
   * Gets the value of the 'meanSeaLevelPressureCount' field.
   */
  public java.lang.Integer getMeanSeaLevelPressureCount() {
    return meanSeaLevelPressureCount;
  }

  /**
   * Sets the value of the 'meanSeaLevelPressureCount' field.
   * @param value the value to set.
   */
  public void setMeanSeaLevelPressureCount(java.lang.Integer value) {
    this.meanSeaLevelPressureCount = value;
  }

  /**
   * Gets the value of the 'meanStationPressure' field.
   */
  public java.lang.Double getMeanStationPressure() {
    return meanStationPressure;
  }

  /**
   * Sets the value of the 'meanStationPressure' field.
   * @param value the value to set.
   */
  public void setMeanStationPressure(java.lang.Double value) {
    this.meanStationPressure = value;
  }

  /**
   * Gets the value of the 'meanStationPressureCount' field.
   */
  public java.lang.Integer getMeanStationPressureCount() {
    return meanStationPressureCount;
  }

  /**
   * Sets the value of the 'meanStationPressureCount' field.
   * @param value the value to set.
   */
  public void setMeanStationPressureCount(java.lang.Integer value) {
    this.meanStationPressureCount = value;
  }

  /**
   * Gets the value of the 'meanVisibility' field.
   */
  public java.lang.Double getMeanVisibility() {
    return meanVisibility;
  }

  /**
   * Sets the value of the 'meanVisibility' field.
   * @param value the value to set.
   */
  public void setMeanVisibility(java.lang.Double value) {
    this.meanVisibility = value;
  }

  /**
   * Gets the value of the 'meanVisibilityCount' field.
   */
  public java.lang.Integer getMeanVisibilityCount() {
    return meanVisibilityCount;
  }

  /**
   * Sets the value of the 'meanVisibilityCount' field.
   * @param value the value to set.
   */
  public void setMeanVisibilityCount(java.lang.Integer value) {
    this.meanVisibilityCount = value;
  }

  /**
   * Gets the value of the 'meanWindSpeed' field.
   */
  public java.lang.Double getMeanWindSpeed() {
    return meanWindSpeed;
  }

  /**
   * Sets the value of the 'meanWindSpeed' field.
   * @param value the value to set.
   */
  public void setMeanWindSpeed(java.lang.Double value) {
    this.meanWindSpeed = value;
  }

  /**
   * Gets the value of the 'meanWindSpeedCount' field.
   */
  public java.lang.Integer getMeanWindSpeedCount() {
    return meanWindSpeedCount;
  }

  /**
   * Sets the value of the 'meanWindSpeedCount' field.
   * @param value the value to set.
   */
  public void setMeanWindSpeedCount(java.lang.Integer value) {
    this.meanWindSpeedCount = value;
  }

  /**
   * Gets the value of the 'maxSustainedWindSpeed' field.
   */
  public java.lang.Double getMaxSustainedWindSpeed() {
    return maxSustainedWindSpeed;
  }

  /**
   * Sets the value of the 'maxSustainedWindSpeed' field.
   * @param value the value to set.
   */
  public void setMaxSustainedWindSpeed(java.lang.Double value) {
    this.maxSustainedWindSpeed = value;
  }

  /**
   * Gets the value of the 'maxGustWindSpeed' field.
   */
  public java.lang.Double getMaxGustWindSpeed() {
    return maxGustWindSpeed;
  }

  /**
   * Sets the value of the 'maxGustWindSpeed' field.
   * @param value the value to set.
   */
  public void setMaxGustWindSpeed(java.lang.Double value) {
    this.maxGustWindSpeed = value;
  }

  /**
   * Gets the value of the 'maxTemp' field.
   */
  public java.lang.Double getMaxTemp() {
    return maxTemp;
  }

  /**
   * Sets the value of the 'maxTemp' field.
   * @param value the value to set.
   */
  public void setMaxTemp(java.lang.Double value) {
    this.maxTemp = value;
  }

  /**
   * Gets the value of the 'maxTempFlag' field.
   */
  public java.lang.CharSequence getMaxTempFlag() {
    return maxTempFlag;
  }

  /**
   * Sets the value of the 'maxTempFlag' field.
   * @param value the value to set.
   */
  public void setMaxTempFlag(java.lang.CharSequence value) {
    this.maxTempFlag = value;
  }

  /**
   * Gets the value of the 'minTemp' field.
   */
  public java.lang.Double getMinTemp() {
    return minTemp;
  }

  /**
   * Sets the value of the 'minTemp' field.
   * @param value the value to set.
   */
  public void setMinTemp(java.lang.Double value) {
    this.minTemp = value;
  }

  /**
   * Gets the value of the 'minTempFlag' field.
   */
  public java.lang.CharSequence getMinTempFlag() {
    return minTempFlag;
  }

  /**
   * Sets the value of the 'minTempFlag' field.
   * @param value the value to set.
   */
  public void setMinTempFlag(java.lang.CharSequence value) {
    this.minTempFlag = value;
  }

  /**
   * Gets the value of the 'totalPrecipitation' field.
   */
  public java.lang.Double getTotalPrecipitation() {
    return totalPrecipitation;
  }

  /**
   * Sets the value of the 'totalPrecipitation' field.
   * @param value the value to set.
   */
  public void setTotalPrecipitation(java.lang.Double value) {
    this.totalPrecipitation = value;
  }

  /**
   * Gets the value of the 'totalPrecipitationFlag' field.
   */
  public java.lang.CharSequence getTotalPrecipitationFlag() {
    return totalPrecipitationFlag;
  }

  /**
   * Sets the value of the 'totalPrecipitationFlag' field.
   * @param value the value to set.
   */
  public void setTotalPrecipitationFlag(java.lang.CharSequence value) {
    this.totalPrecipitationFlag = value;
  }

  /**
   * Gets the value of the 'snowDepth' field.
   */
  public java.lang.Double getSnowDepth() {
    return snowDepth;
  }

  /**
   * Sets the value of the 'snowDepth' field.
   * @param value the value to set.
   */
  public void setSnowDepth(java.lang.Double value) {
    this.snowDepth = value;
  }

  /**
   * Gets the value of the 'hasFog' field.
   */
  public java.lang.Boolean getHasFog() {
    return hasFog;
  }

  /**
   * Sets the value of the 'hasFog' field.
   * @param value the value to set.
   */
  public void setHasFog(java.lang.Boolean value) {
    this.hasFog = value;
  }

  /**
   * Gets the value of the 'hasRain' field.
   */
  public java.lang.Boolean getHasRain() {
    return hasRain;
  }

  /**
   * Sets the value of the 'hasRain' field.
   * @param value the value to set.
   */
  public void setHasRain(java.lang.Boolean value) {
    this.hasRain = value;
  }

  /**
   * Gets the value of the 'hasSnow' field.
   */
  public java.lang.Boolean getHasSnow() {
    return hasSnow;
  }

  /**
   * Sets the value of the 'hasSnow' field.
   * @param value the value to set.
   */
  public void setHasSnow(java.lang.Boolean value) {
    this.hasSnow = value;
  }

  /**
   * Gets the value of the 'hasHail' field.
   */
  public java.lang.Boolean getHasHail() {
    return hasHail;
  }

  /**
   * Sets the value of the 'hasHail' field.
   * @param value the value to set.
   */
  public void setHasHail(java.lang.Boolean value) {
    this.hasHail = value;
  }

  /**
   * Gets the value of the 'hasThunder' field.
   */
  public java.lang.Boolean getHasThunder() {
    return hasThunder;
  }

  /**
   * Sets the value of the 'hasThunder' field.
   * @param value the value to set.
   */
  public void setHasThunder(java.lang.Boolean value) {
    this.hasThunder = value;
  }

  /**
   * Gets the value of the 'hasTornado' field.
   */
  public java.lang.Boolean getHasTornado() {
    return hasTornado;
  }

  /**
   * Sets the value of the 'hasTornado' field.
   * @param value the value to set.
   */
  public void setHasTornado(java.lang.Boolean value) {
    this.hasTornado = value;
  }

  /** Creates a new WeatherData RecordBuilder */
  public static com.my.rdd.WeatherData.Builder newBuilder() {
    return new com.my.rdd.WeatherData.Builder();
  }
  
  /** Creates a new WeatherData RecordBuilder by copying an existing Builder */
  public static com.my.rdd.WeatherData.Builder newBuilder(com.my.rdd.WeatherData.Builder other) {
    return new com.my.rdd.WeatherData.Builder(other);
  }
  
  /** Creates a new WeatherData RecordBuilder by copying an existing WeatherData instance */
  public static com.my.rdd.WeatherData.Builder newBuilder(com.my.rdd.WeatherData other) {
    return new com.my.rdd.WeatherData.Builder(other);
  }
  
  /**
   * RecordBuilder for WeatherData instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<WeatherData>
    implements org.apache.avro.data.RecordBuilder<WeatherData> {

    private java.lang.CharSequence stationId;
    private java.lang.CharSequence year;
    private java.lang.CharSequence month;
    private java.lang.CharSequence day;
    private double meanTemp;
    private int meanTempCount;
    private double meanDewPointTemp;
    private int meanDewPointTempCount;
    private double meanSeaLevelPressure;
    private int meanSeaLevelPressureCount;
    private double meanStationPressure;
    private int meanStationPressureCount;
    private double meanVisibility;
    private int meanVisibilityCount;
    private double meanWindSpeed;
    private int meanWindSpeedCount;
    private double maxSustainedWindSpeed;
    private double maxGustWindSpeed;
    private double maxTemp;
    private java.lang.CharSequence maxTempFlag;
    private double minTemp;
    private java.lang.CharSequence minTempFlag;
    private double totalPrecipitation;
    private java.lang.CharSequence totalPrecipitationFlag;
    private double snowDepth;
    private boolean hasFog;
    private boolean hasRain;
    private boolean hasSnow;
    private boolean hasHail;
    private boolean hasThunder;
    private boolean hasTornado;

    /** Creates a new Builder */
    private Builder() {
      super(com.my.rdd.WeatherData.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.my.rdd.WeatherData.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.stationId)) {
        this.stationId = data().deepCopy(fields()[0].schema(), other.stationId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.year)) {
        this.year = data().deepCopy(fields()[1].schema(), other.year);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.month)) {
        this.month = data().deepCopy(fields()[2].schema(), other.month);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.day)) {
        this.day = data().deepCopy(fields()[3].schema(), other.day);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.meanTemp)) {
        this.meanTemp = data().deepCopy(fields()[4].schema(), other.meanTemp);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.meanTempCount)) {
        this.meanTempCount = data().deepCopy(fields()[5].schema(), other.meanTempCount);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.meanDewPointTemp)) {
        this.meanDewPointTemp = data().deepCopy(fields()[6].schema(), other.meanDewPointTemp);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.meanDewPointTempCount)) {
        this.meanDewPointTempCount = data().deepCopy(fields()[7].schema(), other.meanDewPointTempCount);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.meanSeaLevelPressure)) {
        this.meanSeaLevelPressure = data().deepCopy(fields()[8].schema(), other.meanSeaLevelPressure);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.meanSeaLevelPressureCount)) {
        this.meanSeaLevelPressureCount = data().deepCopy(fields()[9].schema(), other.meanSeaLevelPressureCount);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.meanStationPressure)) {
        this.meanStationPressure = data().deepCopy(fields()[10].schema(), other.meanStationPressure);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.meanStationPressureCount)) {
        this.meanStationPressureCount = data().deepCopy(fields()[11].schema(), other.meanStationPressureCount);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.meanVisibility)) {
        this.meanVisibility = data().deepCopy(fields()[12].schema(), other.meanVisibility);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.meanVisibilityCount)) {
        this.meanVisibilityCount = data().deepCopy(fields()[13].schema(), other.meanVisibilityCount);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.meanWindSpeed)) {
        this.meanWindSpeed = data().deepCopy(fields()[14].schema(), other.meanWindSpeed);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.meanWindSpeedCount)) {
        this.meanWindSpeedCount = data().deepCopy(fields()[15].schema(), other.meanWindSpeedCount);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.maxSustainedWindSpeed)) {
        this.maxSustainedWindSpeed = data().deepCopy(fields()[16].schema(), other.maxSustainedWindSpeed);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.maxGustWindSpeed)) {
        this.maxGustWindSpeed = data().deepCopy(fields()[17].schema(), other.maxGustWindSpeed);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.maxTemp)) {
        this.maxTemp = data().deepCopy(fields()[18].schema(), other.maxTemp);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.maxTempFlag)) {
        this.maxTempFlag = data().deepCopy(fields()[19].schema(), other.maxTempFlag);
        fieldSetFlags()[19] = true;
      }
      if (isValidValue(fields()[20], other.minTemp)) {
        this.minTemp = data().deepCopy(fields()[20].schema(), other.minTemp);
        fieldSetFlags()[20] = true;
      }
      if (isValidValue(fields()[21], other.minTempFlag)) {
        this.minTempFlag = data().deepCopy(fields()[21].schema(), other.minTempFlag);
        fieldSetFlags()[21] = true;
      }
      if (isValidValue(fields()[22], other.totalPrecipitation)) {
        this.totalPrecipitation = data().deepCopy(fields()[22].schema(), other.totalPrecipitation);
        fieldSetFlags()[22] = true;
      }
      if (isValidValue(fields()[23], other.totalPrecipitationFlag)) {
        this.totalPrecipitationFlag = data().deepCopy(fields()[23].schema(), other.totalPrecipitationFlag);
        fieldSetFlags()[23] = true;
      }
      if (isValidValue(fields()[24], other.snowDepth)) {
        this.snowDepth = data().deepCopy(fields()[24].schema(), other.snowDepth);
        fieldSetFlags()[24] = true;
      }
      if (isValidValue(fields()[25], other.hasFog)) {
        this.hasFog = data().deepCopy(fields()[25].schema(), other.hasFog);
        fieldSetFlags()[25] = true;
      }
      if (isValidValue(fields()[26], other.hasRain)) {
        this.hasRain = data().deepCopy(fields()[26].schema(), other.hasRain);
        fieldSetFlags()[26] = true;
      }
      if (isValidValue(fields()[27], other.hasSnow)) {
        this.hasSnow = data().deepCopy(fields()[27].schema(), other.hasSnow);
        fieldSetFlags()[27] = true;
      }
      if (isValidValue(fields()[28], other.hasHail)) {
        this.hasHail = data().deepCopy(fields()[28].schema(), other.hasHail);
        fieldSetFlags()[28] = true;
      }
      if (isValidValue(fields()[29], other.hasThunder)) {
        this.hasThunder = data().deepCopy(fields()[29].schema(), other.hasThunder);
        fieldSetFlags()[29] = true;
      }
      if (isValidValue(fields()[30], other.hasTornado)) {
        this.hasTornado = data().deepCopy(fields()[30].schema(), other.hasTornado);
        fieldSetFlags()[30] = true;
      }
    }
    
    /** Creates a Builder by copying an existing WeatherData instance */
    private Builder(com.my.rdd.WeatherData other) {
            super(com.my.rdd.WeatherData.SCHEMA$);
      if (isValidValue(fields()[0], other.stationId)) {
        this.stationId = data().deepCopy(fields()[0].schema(), other.stationId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.year)) {
        this.year = data().deepCopy(fields()[1].schema(), other.year);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.month)) {
        this.month = data().deepCopy(fields()[2].schema(), other.month);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.day)) {
        this.day = data().deepCopy(fields()[3].schema(), other.day);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.meanTemp)) {
        this.meanTemp = data().deepCopy(fields()[4].schema(), other.meanTemp);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.meanTempCount)) {
        this.meanTempCount = data().deepCopy(fields()[5].schema(), other.meanTempCount);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.meanDewPointTemp)) {
        this.meanDewPointTemp = data().deepCopy(fields()[6].schema(), other.meanDewPointTemp);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.meanDewPointTempCount)) {
        this.meanDewPointTempCount = data().deepCopy(fields()[7].schema(), other.meanDewPointTempCount);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.meanSeaLevelPressure)) {
        this.meanSeaLevelPressure = data().deepCopy(fields()[8].schema(), other.meanSeaLevelPressure);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.meanSeaLevelPressureCount)) {
        this.meanSeaLevelPressureCount = data().deepCopy(fields()[9].schema(), other.meanSeaLevelPressureCount);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.meanStationPressure)) {
        this.meanStationPressure = data().deepCopy(fields()[10].schema(), other.meanStationPressure);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.meanStationPressureCount)) {
        this.meanStationPressureCount = data().deepCopy(fields()[11].schema(), other.meanStationPressureCount);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.meanVisibility)) {
        this.meanVisibility = data().deepCopy(fields()[12].schema(), other.meanVisibility);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.meanVisibilityCount)) {
        this.meanVisibilityCount = data().deepCopy(fields()[13].schema(), other.meanVisibilityCount);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.meanWindSpeed)) {
        this.meanWindSpeed = data().deepCopy(fields()[14].schema(), other.meanWindSpeed);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.meanWindSpeedCount)) {
        this.meanWindSpeedCount = data().deepCopy(fields()[15].schema(), other.meanWindSpeedCount);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.maxSustainedWindSpeed)) {
        this.maxSustainedWindSpeed = data().deepCopy(fields()[16].schema(), other.maxSustainedWindSpeed);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.maxGustWindSpeed)) {
        this.maxGustWindSpeed = data().deepCopy(fields()[17].schema(), other.maxGustWindSpeed);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.maxTemp)) {
        this.maxTemp = data().deepCopy(fields()[18].schema(), other.maxTemp);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.maxTempFlag)) {
        this.maxTempFlag = data().deepCopy(fields()[19].schema(), other.maxTempFlag);
        fieldSetFlags()[19] = true;
      }
      if (isValidValue(fields()[20], other.minTemp)) {
        this.minTemp = data().deepCopy(fields()[20].schema(), other.minTemp);
        fieldSetFlags()[20] = true;
      }
      if (isValidValue(fields()[21], other.minTempFlag)) {
        this.minTempFlag = data().deepCopy(fields()[21].schema(), other.minTempFlag);
        fieldSetFlags()[21] = true;
      }
      if (isValidValue(fields()[22], other.totalPrecipitation)) {
        this.totalPrecipitation = data().deepCopy(fields()[22].schema(), other.totalPrecipitation);
        fieldSetFlags()[22] = true;
      }
      if (isValidValue(fields()[23], other.totalPrecipitationFlag)) {
        this.totalPrecipitationFlag = data().deepCopy(fields()[23].schema(), other.totalPrecipitationFlag);
        fieldSetFlags()[23] = true;
      }
      if (isValidValue(fields()[24], other.snowDepth)) {
        this.snowDepth = data().deepCopy(fields()[24].schema(), other.snowDepth);
        fieldSetFlags()[24] = true;
      }
      if (isValidValue(fields()[25], other.hasFog)) {
        this.hasFog = data().deepCopy(fields()[25].schema(), other.hasFog);
        fieldSetFlags()[25] = true;
      }
      if (isValidValue(fields()[26], other.hasRain)) {
        this.hasRain = data().deepCopy(fields()[26].schema(), other.hasRain);
        fieldSetFlags()[26] = true;
      }
      if (isValidValue(fields()[27], other.hasSnow)) {
        this.hasSnow = data().deepCopy(fields()[27].schema(), other.hasSnow);
        fieldSetFlags()[27] = true;
      }
      if (isValidValue(fields()[28], other.hasHail)) {
        this.hasHail = data().deepCopy(fields()[28].schema(), other.hasHail);
        fieldSetFlags()[28] = true;
      }
      if (isValidValue(fields()[29], other.hasThunder)) {
        this.hasThunder = data().deepCopy(fields()[29].schema(), other.hasThunder);
        fieldSetFlags()[29] = true;
      }
      if (isValidValue(fields()[30], other.hasTornado)) {
        this.hasTornado = data().deepCopy(fields()[30].schema(), other.hasTornado);
        fieldSetFlags()[30] = true;
      }
    }

    /** Gets the value of the 'stationId' field */
    public java.lang.CharSequence getStationId() {
      return stationId;
    }
    
    /** Sets the value of the 'stationId' field */
    public com.my.rdd.WeatherData.Builder setStationId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.stationId = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'stationId' field has been set */
    public boolean hasStationId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'stationId' field */
    public com.my.rdd.WeatherData.Builder clearStationId() {
      stationId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'year' field */
    public java.lang.CharSequence getYear() {
      return year;
    }
    
    /** Sets the value of the 'year' field */
    public com.my.rdd.WeatherData.Builder setYear(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.year = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'year' field has been set */
    public boolean hasYear() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'year' field */
    public com.my.rdd.WeatherData.Builder clearYear() {
      year = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'month' field */
    public java.lang.CharSequence getMonth() {
      return month;
    }
    
    /** Sets the value of the 'month' field */
    public com.my.rdd.WeatherData.Builder setMonth(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.month = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'month' field has been set */
    public boolean hasMonth() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'month' field */
    public com.my.rdd.WeatherData.Builder clearMonth() {
      month = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'day' field */
    public java.lang.CharSequence getDay() {
      return day;
    }
    
    /** Sets the value of the 'day' field */
    public com.my.rdd.WeatherData.Builder setDay(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.day = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'day' field has been set */
    public boolean hasDay() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'day' field */
    public com.my.rdd.WeatherData.Builder clearDay() {
      day = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'meanTemp' field */
    public java.lang.Double getMeanTemp() {
      return meanTemp;
    }
    
    /** Sets the value of the 'meanTemp' field */
    public com.my.rdd.WeatherData.Builder setMeanTemp(double value) {
      validate(fields()[4], value);
      this.meanTemp = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'meanTemp' field has been set */
    public boolean hasMeanTemp() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'meanTemp' field */
    public com.my.rdd.WeatherData.Builder clearMeanTemp() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'meanTempCount' field */
    public java.lang.Integer getMeanTempCount() {
      return meanTempCount;
    }
    
    /** Sets the value of the 'meanTempCount' field */
    public com.my.rdd.WeatherData.Builder setMeanTempCount(int value) {
      validate(fields()[5], value);
      this.meanTempCount = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'meanTempCount' field has been set */
    public boolean hasMeanTempCount() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'meanTempCount' field */
    public com.my.rdd.WeatherData.Builder clearMeanTempCount() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'meanDewPointTemp' field */
    public java.lang.Double getMeanDewPointTemp() {
      return meanDewPointTemp;
    }
    
    /** Sets the value of the 'meanDewPointTemp' field */
    public com.my.rdd.WeatherData.Builder setMeanDewPointTemp(double value) {
      validate(fields()[6], value);
      this.meanDewPointTemp = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'meanDewPointTemp' field has been set */
    public boolean hasMeanDewPointTemp() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'meanDewPointTemp' field */
    public com.my.rdd.WeatherData.Builder clearMeanDewPointTemp() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'meanDewPointTempCount' field */
    public java.lang.Integer getMeanDewPointTempCount() {
      return meanDewPointTempCount;
    }
    
    /** Sets the value of the 'meanDewPointTempCount' field */
    public com.my.rdd.WeatherData.Builder setMeanDewPointTempCount(int value) {
      validate(fields()[7], value);
      this.meanDewPointTempCount = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'meanDewPointTempCount' field has been set */
    public boolean hasMeanDewPointTempCount() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'meanDewPointTempCount' field */
    public com.my.rdd.WeatherData.Builder clearMeanDewPointTempCount() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'meanSeaLevelPressure' field */
    public java.lang.Double getMeanSeaLevelPressure() {
      return meanSeaLevelPressure;
    }
    
    /** Sets the value of the 'meanSeaLevelPressure' field */
    public com.my.rdd.WeatherData.Builder setMeanSeaLevelPressure(double value) {
      validate(fields()[8], value);
      this.meanSeaLevelPressure = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'meanSeaLevelPressure' field has been set */
    public boolean hasMeanSeaLevelPressure() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'meanSeaLevelPressure' field */
    public com.my.rdd.WeatherData.Builder clearMeanSeaLevelPressure() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'meanSeaLevelPressureCount' field */
    public java.lang.Integer getMeanSeaLevelPressureCount() {
      return meanSeaLevelPressureCount;
    }
    
    /** Sets the value of the 'meanSeaLevelPressureCount' field */
    public com.my.rdd.WeatherData.Builder setMeanSeaLevelPressureCount(int value) {
      validate(fields()[9], value);
      this.meanSeaLevelPressureCount = value;
      fieldSetFlags()[9] = true;
      return this; 
    }
    
    /** Checks whether the 'meanSeaLevelPressureCount' field has been set */
    public boolean hasMeanSeaLevelPressureCount() {
      return fieldSetFlags()[9];
    }
    
    /** Clears the value of the 'meanSeaLevelPressureCount' field */
    public com.my.rdd.WeatherData.Builder clearMeanSeaLevelPressureCount() {
      fieldSetFlags()[9] = false;
      return this;
    }

    /** Gets the value of the 'meanStationPressure' field */
    public java.lang.Double getMeanStationPressure() {
      return meanStationPressure;
    }
    
    /** Sets the value of the 'meanStationPressure' field */
    public com.my.rdd.WeatherData.Builder setMeanStationPressure(double value) {
      validate(fields()[10], value);
      this.meanStationPressure = value;
      fieldSetFlags()[10] = true;
      return this; 
    }
    
    /** Checks whether the 'meanStationPressure' field has been set */
    public boolean hasMeanStationPressure() {
      return fieldSetFlags()[10];
    }
    
    /** Clears the value of the 'meanStationPressure' field */
    public com.my.rdd.WeatherData.Builder clearMeanStationPressure() {
      fieldSetFlags()[10] = false;
      return this;
    }

    /** Gets the value of the 'meanStationPressureCount' field */
    public java.lang.Integer getMeanStationPressureCount() {
      return meanStationPressureCount;
    }
    
    /** Sets the value of the 'meanStationPressureCount' field */
    public com.my.rdd.WeatherData.Builder setMeanStationPressureCount(int value) {
      validate(fields()[11], value);
      this.meanStationPressureCount = value;
      fieldSetFlags()[11] = true;
      return this; 
    }
    
    /** Checks whether the 'meanStationPressureCount' field has been set */
    public boolean hasMeanStationPressureCount() {
      return fieldSetFlags()[11];
    }
    
    /** Clears the value of the 'meanStationPressureCount' field */
    public com.my.rdd.WeatherData.Builder clearMeanStationPressureCount() {
      fieldSetFlags()[11] = false;
      return this;
    }

    /** Gets the value of the 'meanVisibility' field */
    public java.lang.Double getMeanVisibility() {
      return meanVisibility;
    }
    
    /** Sets the value of the 'meanVisibility' field */
    public com.my.rdd.WeatherData.Builder setMeanVisibility(double value) {
      validate(fields()[12], value);
      this.meanVisibility = value;
      fieldSetFlags()[12] = true;
      return this; 
    }
    
    /** Checks whether the 'meanVisibility' field has been set */
    public boolean hasMeanVisibility() {
      return fieldSetFlags()[12];
    }
    
    /** Clears the value of the 'meanVisibility' field */
    public com.my.rdd.WeatherData.Builder clearMeanVisibility() {
      fieldSetFlags()[12] = false;
      return this;
    }

    /** Gets the value of the 'meanVisibilityCount' field */
    public java.lang.Integer getMeanVisibilityCount() {
      return meanVisibilityCount;
    }
    
    /** Sets the value of the 'meanVisibilityCount' field */
    public com.my.rdd.WeatherData.Builder setMeanVisibilityCount(int value) {
      validate(fields()[13], value);
      this.meanVisibilityCount = value;
      fieldSetFlags()[13] = true;
      return this; 
    }
    
    /** Checks whether the 'meanVisibilityCount' field has been set */
    public boolean hasMeanVisibilityCount() {
      return fieldSetFlags()[13];
    }
    
    /** Clears the value of the 'meanVisibilityCount' field */
    public com.my.rdd.WeatherData.Builder clearMeanVisibilityCount() {
      fieldSetFlags()[13] = false;
      return this;
    }

    /** Gets the value of the 'meanWindSpeed' field */
    public java.lang.Double getMeanWindSpeed() {
      return meanWindSpeed;
    }
    
    /** Sets the value of the 'meanWindSpeed' field */
    public com.my.rdd.WeatherData.Builder setMeanWindSpeed(double value) {
      validate(fields()[14], value);
      this.meanWindSpeed = value;
      fieldSetFlags()[14] = true;
      return this; 
    }
    
    /** Checks whether the 'meanWindSpeed' field has been set */
    public boolean hasMeanWindSpeed() {
      return fieldSetFlags()[14];
    }
    
    /** Clears the value of the 'meanWindSpeed' field */
    public com.my.rdd.WeatherData.Builder clearMeanWindSpeed() {
      fieldSetFlags()[14] = false;
      return this;
    }

    /** Gets the value of the 'meanWindSpeedCount' field */
    public java.lang.Integer getMeanWindSpeedCount() {
      return meanWindSpeedCount;
    }
    
    /** Sets the value of the 'meanWindSpeedCount' field */
    public com.my.rdd.WeatherData.Builder setMeanWindSpeedCount(int value) {
      validate(fields()[15], value);
      this.meanWindSpeedCount = value;
      fieldSetFlags()[15] = true;
      return this; 
    }
    
    /** Checks whether the 'meanWindSpeedCount' field has been set */
    public boolean hasMeanWindSpeedCount() {
      return fieldSetFlags()[15];
    }
    
    /** Clears the value of the 'meanWindSpeedCount' field */
    public com.my.rdd.WeatherData.Builder clearMeanWindSpeedCount() {
      fieldSetFlags()[15] = false;
      return this;
    }

    /** Gets the value of the 'maxSustainedWindSpeed' field */
    public java.lang.Double getMaxSustainedWindSpeed() {
      return maxSustainedWindSpeed;
    }
    
    /** Sets the value of the 'maxSustainedWindSpeed' field */
    public com.my.rdd.WeatherData.Builder setMaxSustainedWindSpeed(double value) {
      validate(fields()[16], value);
      this.maxSustainedWindSpeed = value;
      fieldSetFlags()[16] = true;
      return this; 
    }
    
    /** Checks whether the 'maxSustainedWindSpeed' field has been set */
    public boolean hasMaxSustainedWindSpeed() {
      return fieldSetFlags()[16];
    }
    
    /** Clears the value of the 'maxSustainedWindSpeed' field */
    public com.my.rdd.WeatherData.Builder clearMaxSustainedWindSpeed() {
      fieldSetFlags()[16] = false;
      return this;
    }

    /** Gets the value of the 'maxGustWindSpeed' field */
    public java.lang.Double getMaxGustWindSpeed() {
      return maxGustWindSpeed;
    }
    
    /** Sets the value of the 'maxGustWindSpeed' field */
    public com.my.rdd.WeatherData.Builder setMaxGustWindSpeed(double value) {
      validate(fields()[17], value);
      this.maxGustWindSpeed = value;
      fieldSetFlags()[17] = true;
      return this; 
    }
    
    /** Checks whether the 'maxGustWindSpeed' field has been set */
    public boolean hasMaxGustWindSpeed() {
      return fieldSetFlags()[17];
    }
    
    /** Clears the value of the 'maxGustWindSpeed' field */
    public com.my.rdd.WeatherData.Builder clearMaxGustWindSpeed() {
      fieldSetFlags()[17] = false;
      return this;
    }

    /** Gets the value of the 'maxTemp' field */
    public java.lang.Double getMaxTemp() {
      return maxTemp;
    }
    
    /** Sets the value of the 'maxTemp' field */
    public com.my.rdd.WeatherData.Builder setMaxTemp(double value) {
      validate(fields()[18], value);
      this.maxTemp = value;
      fieldSetFlags()[18] = true;
      return this; 
    }
    
    /** Checks whether the 'maxTemp' field has been set */
    public boolean hasMaxTemp() {
      return fieldSetFlags()[18];
    }
    
    /** Clears the value of the 'maxTemp' field */
    public com.my.rdd.WeatherData.Builder clearMaxTemp() {
      fieldSetFlags()[18] = false;
      return this;
    }

    /** Gets the value of the 'maxTempFlag' field */
    public java.lang.CharSequence getMaxTempFlag() {
      return maxTempFlag;
    }
    
    /** Sets the value of the 'maxTempFlag' field */
    public com.my.rdd.WeatherData.Builder setMaxTempFlag(java.lang.CharSequence value) {
      validate(fields()[19], value);
      this.maxTempFlag = value;
      fieldSetFlags()[19] = true;
      return this; 
    }
    
    /** Checks whether the 'maxTempFlag' field has been set */
    public boolean hasMaxTempFlag() {
      return fieldSetFlags()[19];
    }
    
    /** Clears the value of the 'maxTempFlag' field */
    public com.my.rdd.WeatherData.Builder clearMaxTempFlag() {
      maxTempFlag = null;
      fieldSetFlags()[19] = false;
      return this;
    }

    /** Gets the value of the 'minTemp' field */
    public java.lang.Double getMinTemp() {
      return minTemp;
    }
    
    /** Sets the value of the 'minTemp' field */
    public com.my.rdd.WeatherData.Builder setMinTemp(double value) {
      validate(fields()[20], value);
      this.minTemp = value;
      fieldSetFlags()[20] = true;
      return this; 
    }
    
    /** Checks whether the 'minTemp' field has been set */
    public boolean hasMinTemp() {
      return fieldSetFlags()[20];
    }
    
    /** Clears the value of the 'minTemp' field */
    public com.my.rdd.WeatherData.Builder clearMinTemp() {
      fieldSetFlags()[20] = false;
      return this;
    }

    /** Gets the value of the 'minTempFlag' field */
    public java.lang.CharSequence getMinTempFlag() {
      return minTempFlag;
    }
    
    /** Sets the value of the 'minTempFlag' field */
    public com.my.rdd.WeatherData.Builder setMinTempFlag(java.lang.CharSequence value) {
      validate(fields()[21], value);
      this.minTempFlag = value;
      fieldSetFlags()[21] = true;
      return this; 
    }
    
    /** Checks whether the 'minTempFlag' field has been set */
    public boolean hasMinTempFlag() {
      return fieldSetFlags()[21];
    }
    
    /** Clears the value of the 'minTempFlag' field */
    public com.my.rdd.WeatherData.Builder clearMinTempFlag() {
      minTempFlag = null;
      fieldSetFlags()[21] = false;
      return this;
    }

    /** Gets the value of the 'totalPrecipitation' field */
    public java.lang.Double getTotalPrecipitation() {
      return totalPrecipitation;
    }
    
    /** Sets the value of the 'totalPrecipitation' field */
    public com.my.rdd.WeatherData.Builder setTotalPrecipitation(double value) {
      validate(fields()[22], value);
      this.totalPrecipitation = value;
      fieldSetFlags()[22] = true;
      return this; 
    }
    
    /** Checks whether the 'totalPrecipitation' field has been set */
    public boolean hasTotalPrecipitation() {
      return fieldSetFlags()[22];
    }
    
    /** Clears the value of the 'totalPrecipitation' field */
    public com.my.rdd.WeatherData.Builder clearTotalPrecipitation() {
      fieldSetFlags()[22] = false;
      return this;
    }

    /** Gets the value of the 'totalPrecipitationFlag' field */
    public java.lang.CharSequence getTotalPrecipitationFlag() {
      return totalPrecipitationFlag;
    }
    
    /** Sets the value of the 'totalPrecipitationFlag' field */
    public com.my.rdd.WeatherData.Builder setTotalPrecipitationFlag(java.lang.CharSequence value) {
      validate(fields()[23], value);
      this.totalPrecipitationFlag = value;
      fieldSetFlags()[23] = true;
      return this; 
    }
    
    /** Checks whether the 'totalPrecipitationFlag' field has been set */
    public boolean hasTotalPrecipitationFlag() {
      return fieldSetFlags()[23];
    }
    
    /** Clears the value of the 'totalPrecipitationFlag' field */
    public com.my.rdd.WeatherData.Builder clearTotalPrecipitationFlag() {
      totalPrecipitationFlag = null;
      fieldSetFlags()[23] = false;
      return this;
    }

    /** Gets the value of the 'snowDepth' field */
    public java.lang.Double getSnowDepth() {
      return snowDepth;
    }
    
    /** Sets the value of the 'snowDepth' field */
    public com.my.rdd.WeatherData.Builder setSnowDepth(double value) {
      validate(fields()[24], value);
      this.snowDepth = value;
      fieldSetFlags()[24] = true;
      return this; 
    }
    
    /** Checks whether the 'snowDepth' field has been set */
    public boolean hasSnowDepth() {
      return fieldSetFlags()[24];
    }
    
    /** Clears the value of the 'snowDepth' field */
    public com.my.rdd.WeatherData.Builder clearSnowDepth() {
      fieldSetFlags()[24] = false;
      return this;
    }

    /** Gets the value of the 'hasFog' field */
    public java.lang.Boolean getHasFog() {
      return hasFog;
    }
    
    /** Sets the value of the 'hasFog' field */
    public com.my.rdd.WeatherData.Builder setHasFog(boolean value) {
      validate(fields()[25], value);
      this.hasFog = value;
      fieldSetFlags()[25] = true;
      return this; 
    }
    
    /** Checks whether the 'hasFog' field has been set */
    public boolean hasHasFog() {
      return fieldSetFlags()[25];
    }
    
    /** Clears the value of the 'hasFog' field */
    public com.my.rdd.WeatherData.Builder clearHasFog() {
      fieldSetFlags()[25] = false;
      return this;
    }

    /** Gets the value of the 'hasRain' field */
    public java.lang.Boolean getHasRain() {
      return hasRain;
    }
    
    /** Sets the value of the 'hasRain' field */
    public com.my.rdd.WeatherData.Builder setHasRain(boolean value) {
      validate(fields()[26], value);
      this.hasRain = value;
      fieldSetFlags()[26] = true;
      return this; 
    }
    
    /** Checks whether the 'hasRain' field has been set */
    public boolean hasHasRain() {
      return fieldSetFlags()[26];
    }
    
    /** Clears the value of the 'hasRain' field */
    public com.my.rdd.WeatherData.Builder clearHasRain() {
      fieldSetFlags()[26] = false;
      return this;
    }

    /** Gets the value of the 'hasSnow' field */
    public java.lang.Boolean getHasSnow() {
      return hasSnow;
    }
    
    /** Sets the value of the 'hasSnow' field */
    public com.my.rdd.WeatherData.Builder setHasSnow(boolean value) {
      validate(fields()[27], value);
      this.hasSnow = value;
      fieldSetFlags()[27] = true;
      return this; 
    }
    
    /** Checks whether the 'hasSnow' field has been set */
    public boolean hasHasSnow() {
      return fieldSetFlags()[27];
    }
    
    /** Clears the value of the 'hasSnow' field */
    public com.my.rdd.WeatherData.Builder clearHasSnow() {
      fieldSetFlags()[27] = false;
      return this;
    }

    /** Gets the value of the 'hasHail' field */
    public java.lang.Boolean getHasHail() {
      return hasHail;
    }
    
    /** Sets the value of the 'hasHail' field */
    public com.my.rdd.WeatherData.Builder setHasHail(boolean value) {
      validate(fields()[28], value);
      this.hasHail = value;
      fieldSetFlags()[28] = true;
      return this; 
    }
    
    /** Checks whether the 'hasHail' field has been set */
    public boolean hasHasHail() {
      return fieldSetFlags()[28];
    }
    
    /** Clears the value of the 'hasHail' field */
    public com.my.rdd.WeatherData.Builder clearHasHail() {
      fieldSetFlags()[28] = false;
      return this;
    }

    /** Gets the value of the 'hasThunder' field */
    public java.lang.Boolean getHasThunder() {
      return hasThunder;
    }
    
    /** Sets the value of the 'hasThunder' field */
    public com.my.rdd.WeatherData.Builder setHasThunder(boolean value) {
      validate(fields()[29], value);
      this.hasThunder = value;
      fieldSetFlags()[29] = true;
      return this; 
    }
    
    /** Checks whether the 'hasThunder' field has been set */
    public boolean hasHasThunder() {
      return fieldSetFlags()[29];
    }
    
    /** Clears the value of the 'hasThunder' field */
    public com.my.rdd.WeatherData.Builder clearHasThunder() {
      fieldSetFlags()[29] = false;
      return this;
    }

    /** Gets the value of the 'hasTornado' field */
    public java.lang.Boolean getHasTornado() {
      return hasTornado;
    }
    
    /** Sets the value of the 'hasTornado' field */
    public com.my.rdd.WeatherData.Builder setHasTornado(boolean value) {
      validate(fields()[30], value);
      this.hasTornado = value;
      fieldSetFlags()[30] = true;
      return this; 
    }
    
    /** Checks whether the 'hasTornado' field has been set */
    public boolean hasHasTornado() {
      return fieldSetFlags()[30];
    }
    
    /** Clears the value of the 'hasTornado' field */
    public com.my.rdd.WeatherData.Builder clearHasTornado() {
      fieldSetFlags()[30] = false;
      return this;
    }

    @Override
    public WeatherData build() {
      try {
        WeatherData record = new WeatherData();
        record.stationId = fieldSetFlags()[0] ? this.stationId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.year = fieldSetFlags()[1] ? this.year : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.month = fieldSetFlags()[2] ? this.month : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.day = fieldSetFlags()[3] ? this.day : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.meanTemp = fieldSetFlags()[4] ? this.meanTemp : (java.lang.Double) defaultValue(fields()[4]);
        record.meanTempCount = fieldSetFlags()[5] ? this.meanTempCount : (java.lang.Integer) defaultValue(fields()[5]);
        record.meanDewPointTemp = fieldSetFlags()[6] ? this.meanDewPointTemp : (java.lang.Double) defaultValue(fields()[6]);
        record.meanDewPointTempCount = fieldSetFlags()[7] ? this.meanDewPointTempCount : (java.lang.Integer) defaultValue(fields()[7]);
        record.meanSeaLevelPressure = fieldSetFlags()[8] ? this.meanSeaLevelPressure : (java.lang.Double) defaultValue(fields()[8]);
        record.meanSeaLevelPressureCount = fieldSetFlags()[9] ? this.meanSeaLevelPressureCount : (java.lang.Integer) defaultValue(fields()[9]);
        record.meanStationPressure = fieldSetFlags()[10] ? this.meanStationPressure : (java.lang.Double) defaultValue(fields()[10]);
        record.meanStationPressureCount = fieldSetFlags()[11] ? this.meanStationPressureCount : (java.lang.Integer) defaultValue(fields()[11]);
        record.meanVisibility = fieldSetFlags()[12] ? this.meanVisibility : (java.lang.Double) defaultValue(fields()[12]);
        record.meanVisibilityCount = fieldSetFlags()[13] ? this.meanVisibilityCount : (java.lang.Integer) defaultValue(fields()[13]);
        record.meanWindSpeed = fieldSetFlags()[14] ? this.meanWindSpeed : (java.lang.Double) defaultValue(fields()[14]);
        record.meanWindSpeedCount = fieldSetFlags()[15] ? this.meanWindSpeedCount : (java.lang.Integer) defaultValue(fields()[15]);
        record.maxSustainedWindSpeed = fieldSetFlags()[16] ? this.maxSustainedWindSpeed : (java.lang.Double) defaultValue(fields()[16]);
        record.maxGustWindSpeed = fieldSetFlags()[17] ? this.maxGustWindSpeed : (java.lang.Double) defaultValue(fields()[17]);
        record.maxTemp = fieldSetFlags()[18] ? this.maxTemp : (java.lang.Double) defaultValue(fields()[18]);
        record.maxTempFlag = fieldSetFlags()[19] ? this.maxTempFlag : (java.lang.CharSequence) defaultValue(fields()[19]);
        record.minTemp = fieldSetFlags()[20] ? this.minTemp : (java.lang.Double) defaultValue(fields()[20]);
        record.minTempFlag = fieldSetFlags()[21] ? this.minTempFlag : (java.lang.CharSequence) defaultValue(fields()[21]);
        record.totalPrecipitation = fieldSetFlags()[22] ? this.totalPrecipitation : (java.lang.Double) defaultValue(fields()[22]);
        record.totalPrecipitationFlag = fieldSetFlags()[23] ? this.totalPrecipitationFlag : (java.lang.CharSequence) defaultValue(fields()[23]);
        record.snowDepth = fieldSetFlags()[24] ? this.snowDepth : (java.lang.Double) defaultValue(fields()[24]);
        record.hasFog = fieldSetFlags()[25] ? this.hasFog : (java.lang.Boolean) defaultValue(fields()[25]);
        record.hasRain = fieldSetFlags()[26] ? this.hasRain : (java.lang.Boolean) defaultValue(fields()[26]);
        record.hasSnow = fieldSetFlags()[27] ? this.hasSnow : (java.lang.Boolean) defaultValue(fields()[27]);
        record.hasHail = fieldSetFlags()[28] ? this.hasHail : (java.lang.Boolean) defaultValue(fields()[28]);
        record.hasThunder = fieldSetFlags()[29] ? this.hasThunder : (java.lang.Boolean) defaultValue(fields()[29]);
        record.hasTornado = fieldSetFlags()[30] ? this.hasTornado : (java.lang.Boolean) defaultValue(fields()[30]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
